version: '3.7'
services:
  mongo:
    image: mongo:3.6

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    volumes:
    - .:/application
    environment:
      RAILS_ENV: development
      AWS_REGION: us-east-1
      MONGO_PRIMARY_HOST: mongo
      MONGO_ROCKETJOB_HOST: mongo

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/admin/health_check"]
      interval: 30s
      timeout: 10s
      retries: 10

