client_options: &client_options
  read:
    mode:             :primary
  write:
    w:                0
  max_pool_size:      50
  min_pool_size:      10
  connect_timeout:    5
  socket_timeout:     300
  wait_queue_timeout: 5


configuration: &configuration
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= SecretConfig.fetch("mongo/primary/database") %>
      hosts:
        - <%= SecretConfig.fetch("mongo/primary/host") %>
      options:

    rocketjob: &default_development
      database: <%= SecretConfig.fetch("mongo/rocketjob/database") %>
      hosts:
        - <%= SecretConfig.fetch("mongo/rocketjob/host") %>
      options:
        <<: *client_options
        write:
          w:   0
        max_pool_size: 5
        min_pool_size: 1

    rocketjob_slices:
      <<: *default_development


development:
  <<: *configuration

test:
  <<: *configuration

production:
  <<: *configuration

